package br.com.jorgemelo.nimbusfilemanager.shared.domain.enums;

public enum MovementReason {

	NONE,

	TARGET_EXISTS, DUPLICATE_TARGET, OVERWRITE_DISABLED, DUPLICATE_QUARANTINED, CONVERTED_QUARANTINED,

	SOURCE_NOT_FOUND, SOURCE_NOT_PHYSICAL, ALREADY_MOVED, ACCESS_DENIED, IO_ERROR, DATABASE_UPDATE_FAILED,

	INTEGRITY_CHECK_FAILED,

	USER_CANCELLED
}