-- Ten columns were called public_id, and a query joining three of them had to be
-- read with the schema open beside it to know which was which.
--
-- That stopped being a readability preference the moment the catalog started
-- recording facts: an execution, a movement and the fact a file moved each have
-- a public identity, they travel together through the same code, and one of them
-- is an idempotency key while the others are not. The first thing that went
-- wrong was exactly this - an execution's identity used as a fact's identity,
-- which reads as correct in Java and is wrong the moment one execution produces
-- two facts.
--
-- So a public identity now says whose it is. RENAME COLUMN carries the data with
-- it by definition, which is what this migration relies on rather than avoids:
-- these tables hold catalogues years old on the machines this ships to.

-- ============================================================
-- Identities: the public name of this table's own row
-- ============================================================

ALTER TABLE catalog_file RENAME COLUMN public_id TO catalog_file_public_id;
ALTER TABLE execution RENAME COLUMN public_id TO execution_public_id;
ALTER TABLE execution_error RENAME COLUMN public_id TO execution_error_public_id;
ALTER TABLE execution_step RENAME COLUMN public_id TO execution_step_public_id;
ALTER TABLE movement RENAME COLUMN public_id TO movement_public_id;
ALTER TABLE similarity_grouping RENAME COLUMN public_id TO similarity_grouping_public_id;

-- ============================================================
-- References: the public name of somebody else's row
-- ============================================================

-- These three never were identities, and the old names actively said otherwise.
-- duplicate_file_exclusion.public_id was the worst of them: a column named as if
-- it were the exclusion's own identity, holding the identity of the file being
-- excluded, and carrying a foreign key to prove it.
ALTER TABLE duplicate_file_exclusion RENAME COLUMN public_id TO catalog_file_public_id;
ALTER TABLE conversion_item_result RENAME COLUMN media_public_id TO catalog_file_public_id;
ALTER TABLE similarity_group_member RENAME COLUMN media_public_id TO catalog_file_public_id;

-- ============================================================
-- What the names now mean
-- ============================================================

COMMENT ON COLUMN catalog_file.catalog_file_public_id IS
    'Stable public identity of this file, generated by the application as UUIDv7. Never derived from the path, never reused.';
COMMENT ON COLUMN execution.execution_public_id IS
    'Stable public identity of this execution. Identifies the run, not anything the run did to a file.';
COMMENT ON COLUMN movement.movement_public_id IS
    'Stable public identity of one file being moved. One execution may own many of these.';
COMMENT ON COLUMN duplicate_file_exclusion.catalog_file_public_id IS
    'The file being excluded, by its public identity. A reference, not this row identity.';
COMMENT ON COLUMN conversion_item_result.catalog_file_public_id IS
    'The file this result is about, by its public identity. A reference, not this row identity.';
COMMENT ON COLUMN similarity_group_member.catalog_file_public_id IS
    'The file in the group, by its public identity. A reference, not this row identity.';